export enum ProductType {
  ESPRESSO = 'ESPRESSO',
  AMERICANO = 'AMERICANO',
  CAPPUCCINO = 'CAPPUCCINO',
  LATTE = 'LATTE',
  MACCHIATO = 'MACCHIATO',
  MOCHA = 'MOCHA',
  FLAT_WHITE = 'FLAT_WHITE',
  RISTRETTO = 'RISTRETTO',
  CORTADO = 'CORTADO',
  AFFOGATO = 'AFFOGATO',
}
