#Anvarov Abror

#Containeriziation

# This configuration is intended for development purpose, it's **your** responsibility to harden it for production

# Specifies the version of the Docker Compose file format being used.
version: '3'
# Defines the services (containers) to be deployed.
services:
  # The name of the service, representing a Java-based coffee application.
  coffee:
    # The Docker image to use, which is based on OpenJDK 17 for running Java applications.
    image: openjdk:17
    # Environment variables passed to the container, configuring the Java application.
    environment:
      # Java options for memory allocation (512MB max, 256MB min).
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      # Port on which the application will run inside the container.
      - SERVER_PORT=18080
      # Spring profiles activated: production and API documentation.
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      # Enables exporting Prometheus metrics.
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      # JDBC URL for connecting to the PostgreSQL database.
      - SPRING_DATASOURCE_URL=jdbc:postgresql://176.96.243.247:5432/coffee_db
      # Liquibase database URL for schema migrations.
      - SPRING_LIQUIBASE_URL=jdbc:postgresql://176.96.243.247/coffee_db
      # Username for the database.
      - SPRING_DATASOURCE_USERNAME=coffee
      # Password for the database.
      - SPRING_DATASOURCE_PASSWORD=zSAdVunybTjL
      # Configures JPA to show SQL queries in the logs.
      - SPRING_JPA_SHOW_SQL=true
    # Mounting volumes to the container.
    volumes:
      # Maps the local directory with JAR files to the container's `/DATA/jars`.
      - /home/coffee/jars:/DATA/jars
      # Maps the log directory to the container's `/DATA/logs/coffee.log`.
      - /home/coffee/logs:/DATA/logs/coffee.log
      # Syncs the container's timezone with the host system (read-only).
      - /etc/localtime:/etc/localtime:ro
      # The command to run inside the container.
      # Runs the latest version of the `coffee` JAR file located in `/DATA/jars` with specific Java options:
      # - Sets the timezone to Asia/Tashkent.
      # - Sets the file encoding to UTF-8.
      # Logs output to `/DATA/logs/coffee.log`.
      # Keeps the container running using `tail -f /dev/null`.

      # Opening and mapping ports between the host and the container.
    command: bash -c "java -Duser.timezone="Asia/Tashkent" -Dfile.encoding=UTF-8 -jar $$(ls -t /DATA/jars/coffee-*.jar | head -n1) --logging.file=/DATA/logs/coffee.log && tail -f /dev/null"
    # Maps port 18080 of the host to port 18080 of the container.
    ports:
      - '18080:18080'
