# Specifies the version of Docker Compose syntax being used
version: '3'
services:
  # Defines the PostgreSQL service
  postgresql:
    # Uses the official PostgreSQL Docker image, version 16.2
    image: postgres:16.2
    # volumes:
    # Environment variables for configuring the PostgreSQL container
    environment:
      # Specifies the name of the default database to be created
      - POSTGRES_DB=coffee_db
      # Defines the username for the PostgreSQL database
      - POSTGRES_USER=coffee
      # Defines the password for the PostgreSQL user
      - POSTGRES_PASSWORD=zSAdVunybTjL
      # Sets the authentication method to 'trust'
      - POSTGRES_HOST_AUTH_METHOD=trust
      # Exposes PostgreSQL on port 5432 to the host, allowing connections to the database
    ports:
      - '5432:5432'
