## This configuration is intended for development purpose, it's **your** responsibility to harden it for production
#version: '3'
#services:
#  postgresql:
#    image: postgres:16.2
#    # volumes:
#    #   - ~/volumes/jhipster/coffee/postgresql/:/var/lib/postgresql/data/
#    environment:
#      - POSTGRES_DB=coffee_db
#      - POSTGRES_USER=coffee
#      - POSTGRES_PASSWORD=zSAdVunybTjL
#      - POSTGRES_HOST_AUTH_METHOD=trust
#    # If you want to expose these ports outside your dev PC,
#    # remove the "127.0.0.1:" prefix
#    ports:
#      - '5432:5432'
